# Termos técnicos da contabilidade / fiscal
DICIONARIO_CONTABIL = [
    "CNPJ",
    "CPF",
    "ICMS",
    "ISS",
    "IPI",
    "INSS",
    "IRPJ",
    "CSLL",
    "PIS",
    "COFINS",
    "Simples Nacional",
    "Lucro Presumido",
    "Lucro Real",
    "SPED",
    "ECD",
    "ECF",
    "DCTF",
    "EFD",
    "eSocial",
    "SEFAZ",
    "Receita Federal",
    "DARF",
    "DAS",
    "GFIP",
    "FGTS",
    "CTPS",
    "CNAE",
    "NCM",
    "CRC",
    "MEI",
    "Matriz",
    "Filial"
]
